- test/bootloader_test.rb
> Add partial test for bootloader module

- .rubocop.yml
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/include/bootloader/grub2/dialogs.rb
- src/include/bootloader/grub2/helps.rb
- src/include/bootloader/grub2/options.rb
- src/include/bootloader/routines/misc.rb
- src/lib/bootloader/grub2base.rb
- src/modules/BootArch.rb
- src/modules/BootCommon.rb
- src/modules/BootGRUB2.rb
- src/modules/BootGRUB2EFI.rb
- src/modules/Bootloader.rb
- test/boot_arch_test.rb
depends on https://github.com/openSUSE/perl-bootloader/pull/69
> Remove failsafe

- Rakefile
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/include/bootloader/grub/helps.rb
- src/include/bootloader/grub/options.rb
- src/include/bootloader/grub2/options.rb
- src/lib/bootloader/grub2base.rb
- src/lib/bootloader/grub2pwd.rb
- src/modules/BootGRUB2.rb
- src/modules/BootGRUB2EFI.rb
- test/grub2pwd_test.rb
- test/test_helper.rb
Do not merge yet as grub2 is not yet ready. changelog update will be added later to avoid conflicts.
> Unrestricted boot

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/include/bootloader/grub2/dialogs.rb
- src/include/bootloader/grub2/helps.rb
- src/include/bootloader/grub2/options.rb
- src/lib/bootloader/grub2base.rb
- src/lib/bootloader/proposal_client.rb
- test/bootloader_proposal_client_test.rb
- test/grub2pwd_test.rb
- test/udev_mapping_test.rb
> Distro proposal

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/finish_client.rb
- src/lib/bootloader/proposal_client.rb
- src/modules/BootGRUB2.rb
- test/bootloader_finish_client_test.rb
- test/bootloader_proposal_client_test.rb
new translatable string is not problem as it is already used at different location.
> Skip grub2 update

- src/lib/bootloader/device_map.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2base.rb
- src/lib/bootloader/stage1.rb
- test/grub2_test.rb
- test/grub_install_test.rb
- test/test_helper.rb
decrease of test coverage is expected as tests are filtered out now
> Jreidinger config files proto

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/modules/BootArch.rb
- test/boot_arch_test.rb
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Include quiet in cmdline for POWER

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2base.rb
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Set gfxterm to console on POWER

- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2efi.rb
- test/grub2_efi_test.rb
- test/grub2_test.rb
Manual testing showed that I accidentally reverted logic and after reread of mentioned bug report I fix proposal to correct values.
> fix inverted logic for pmbr flag causing not working uefi boot

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- test/grub2_test.rb
@jreidinger I guess it fixes problem when calling disks_order [bsc#975514](https://bugzilla.suse.com/show_bug.cgi?id=975514). Feel free to fix it yourself (as part of your refactoring work) and drop this PR.
Thanks!
> Fix disks_order call

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
- test/data/storage_encrypted_two_levels.yaml
That's just a tentative first version of the fix.
> also check one level up for encryption (bsc #976315)

- .rubocop.yml
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/grub2efi.rb
- src/lib/bootloader/grub_install.rb
- src/lib/bootloader/stage1.rb
- src/lib/bootloader/sysconfig.rb
- test/autoyast_converter_test.rb
- test/grub2_test.rb
- test/mbr_update_test.rb
https://trello.com/c/VlEwlLX4
https://fate.suse.com/316553
> trusted boot

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
Drop yast2-bootloader-devel-doc package ([fate#320356](https://fate.suse.com/320356)).
> Drop *-devel-doc package

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/stage1_proposal.rb
- test/stage1_test.rb
note: this is not fix for bnc#994348 it is just found during debugging it.
> Stage1 proposal fix

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/mbr_update.rb
- src/modules/BootStorage.rb
- test/mbr_update_test.rb
for initial review. I plan to do some manual testing if everything is fine.
Test case included.
> Fix activating mdrad

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2_widgets.rb
- test/grub2_widgets_test.rb
Just a merge of this https://github.com/yast/yast-bootloader/pull/364
> Merging pr#364 into master

- .travis.yml
- Rakefile
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/device_map.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2base.rb
- src/lib/bootloader/mbr_update.rb
- src/lib/bootloader/proposal_client.rb
- src/lib/bootloader/stage1.rb
- src/lib/bootloader/stage1_device.rb
- src/lib/bootloader/stage1_proposal.rb
- src/lib/bootloader/udev_mapping.rb
- src/modules/BootStorage.rb
- src/modules/BootSupportCheck.rb
- src/modules/Bootloader.rb
- test/stage1_test.rb
- test/test_helper.rb
Yes, this is primitive but a first step to setup autosubmission.
For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.
> fixed build with storage-ng

- package/yast2-bootloader.changes
- src/lib/bootloader/grub2efi.rb
- src/lib/bootloader/udev_mapping.rb
- src/modules/BootStorage.rb
For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.
> - make simple EFI proposal work with storage-ng

- Rakefile
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/mbr_update.rb
- src/lib/bootloader/stage1_device.rb
- test/data/storage_dm.yaml
- test/grub2_widgets_test.rb
- test/mbr_update_test.rb
- test/stage1_device_test.rb
Merge `merge_after_SP2_release` branch to `SLE-12-SP2`.
> SLE 12 SP2 merge

- .rubocop.yml
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2efi.rb
- src/modules/BootStorage.rb
This fixes several errors introduced while porting the code to storage-ng in the previous PBI (see descriptions of individual commits for details about those errors) https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi
With these fixes, the UEFI system works for me in qemu.
> Fix UEFI for storage-ng

- test/data/storage-ng/storage_lvm.yaml
See https://github.com/openSUSE/libstorage-ng/pull/174
> Adapt test to new libstorage-id partition ids

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- test/data/storage-ng/msdos_and_gpt.yaml
- test/grub2_test.rb
According to my manual tests, this should fix http://yast-openqa.suse.cz/tests/403#step/install_and_reboot/1
> storage-ng: fixed legacy proposal with GPT

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/stage1_proposal.rb
- src/modules/BootStorage.rb
- test/grub2_test.rb
I guess the tests will fail until https://github.com/yast/yast-storage-ng/pull/137 gets merged and published as RPM.
> Use #with_name_or_partition to DRY the code

- Rakefile
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2efi.rb
- src/lib/bootloader/none_bootloader.rb
- src/lib/bootloader/proposal_client.rb
- src/modules/Bootloader.rb
https://trello.com/c/XDgl2dj7/816-13-casp-new-all-in-one-dialog
https://github.com/yast/yast-yast2/pull/530
> Implement simple_mode -> label_proposal (FATE#322328)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2efi.rb
- src/lib/bootloader/none_bootloader.rb
- src/lib/bootloader/proposal_client.rb
- src/modules/Bootloader.rb
> Implement simple_mode -> label_proposal (FATE#322328) (CASP->master)

- .travis.yml
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/exceptions.rb
- src/lib/bootloader/proposal_client.rb
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
> Handle no mountpoint

- .travis.yml
- Dockerfile
- Rakefile
See https://github.com/openSUSE/packaging_rake_tasks/pull/34.
> add to travis checking of valid documentation

- package/yast2-bootloader.changes
- src/lib/bootloader/proposal_client.rb
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
- test/bootloader_proposal_client_test.rb
intentionally do not increase version.
> Storage timestamp ng

- Dockerfile
- Rakefile
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
* afe92bb Merge pull request #432 from yast/SLE-12-SP3_1043132
* 855e35d scanning correct root partition
> [Review] Request from 'schubi2' @ 'yast/yast-bootloader/review_170623_bnc_1043132'

- src/modules/BootStorage.rb
- src/modules/BootSupportCheck.rb
For https://trello.com/c/lSOCC9R8/643-1-storageng-s-390-bootloader-proposal-failure.
> fixed lookup to handle DASDs

- package/yast2-bootloader.changes
- src/lib/bootloader/stage1_proposal.rb
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
- test/data/storage-ng/prep_partitions.yml
- test/stage1_test.rb
PBI: https://trello.com/c/RAPZuM0j/640-3-storageng-bootloader-bootloader-does-not-detect-prep-boot-partition.
> Fix PReP detection

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/device_map.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2efi.rb
- src/lib/bootloader/mbr_update.rb
- src/lib/bootloader/stage1.rb
- src/lib/bootloader/stage1_device.rb
- src/lib/bootloader/stage1_proposal.rb
- src/modules/BootStorage.rb
- src/modules/BootSupportCheck.rb
- test/test_helper.rb
To be merged right after merging yast2-storage-ng 0.1.32.
> Adapt to cleaned Y2Storage::StorageManager API

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/stage1_proposal.rb
This is for: https://trello.com/c/mUEtIRQN
> not everything is a disk, use libstorage's partitionable instead

- src/lib/bootloader/mbr_update.rb
Most notably, dm devices are not disks in libstorage.
Also, the logic in #to_partition seemed wrong. It must return nil if there
are no partitions, not the main device, as the function using it assumes a
typical partition class is returned.
> more fixes where code assumes disk devices instead of libstorage's partitionable

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/mbr_update.rb
> Fix failed backup

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2base.rb
- src/modules/Bootloader.rb
> mark imported configuration from autoytast as modified from proposal

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/stage1.rb
- test/stage1_test.rb
> Fix custom boot

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/device_map_dialog.rb
https://bugzilla.suse.com/show_bug.cgi?id=1083938
> Missing translation

- package/yast2-bootloader.changes
- src/lib/bootloader/mbr_update.rb
SP3 only. Fixed already in master and storage-ng.
> [WIP] translated udev links in stage1 (bsc#1073827)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/config_dialog.rb
- src/lib/bootloader/exceptions.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/grub2base.rb
- src/modules/Bootloader.rb
- test/grub2_widgets_test.rb
PBI: https://trello.com/c/c66dIsRy/1417-3-15-ga-please-dont-throw-an-exception-on-valid-grubterminal-options
how it looks:
> Serial console

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- test/data/trivial.yaml
- test/udev_mapping_test.rb
it cause failure in test on s390.
Status: ready to go for SLE15
> do not use alias in mocking

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
Bump the version and update changelog for #503 to avoid confusion.
> Fix unit tests

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2efi.rb
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
- test/grub2_test.rb
> fix pmbr propose for udev links

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/modules/BootArch.rb
- test/boot_arch_test.rb
This PR is a backport of #511.
> FIPS fix backport

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/desktop/bootloader.desktop
* 4b0febcc Merge pull request #526 from yast/SLE-15-GA-key
> [Review] Request from 'schubi2' @ 'yast/yast-bootloader/review_180629_merged_with_sles15'

- README.md
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/grub2base.rb
- test/autoyast_converter_test.rb
- test/grub2_widgets_test.rb
- test/grub2base_test.rb
Bnc#1053559
depends on https://github.com/config-files-api/config_files_api_grub2/pull/22
when merged, new CFA for GRUB2 gem based on ^^^ has to be released
> Do not crash with internal error when GRUB_TERMINAL contains multiple values

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/grub2base.rb
- test/autoyast_converter_test.rb
- test/grub2_widgets_test.rb
- test/grub2base_test.rb
See https://github.com/yast/yast-bootloader/pull/528
> Backported patch for bnc#1053559 from SLE-15-SP1

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/bootloader_base.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/write_dialog.rb
- src/modules/Bootloader.rb
- test/bootloader_base_test.rb
- test/bootloader_test.rb
- test/grub2_efi_test.rb
- test/grub2_test.rb
- test/grub2base_test.rb
Related to https://bugzilla.suse.com/show_bug.cgi?id=1089829
> Backported fix for bnc#1089829 from SLE-15-SP1

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1111236
> Improve broken configuration detection

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub_install.rb
- src/modules/BootSupportCheck.rb
- test/grub2_test.rb
- test/grub_install_test.rb
trello: https://trello.com/c/7l3D6O7p/734-sle15-sp1-p3-1125792-bootloader-installation-shows-error-messages-but-appears-to-work-nonetheless
bzilla: https://bugzilla.suse.com/show_bug.cgi?id=1125792
> Relax lvm checks

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/generic_widgets.rb
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/grub2base.rb
- src/modules/BootStorage.rb
- test/boot_storage_test.rb
- test/data/multi_swap.yaml
- test/grub2base_test.rb
in this PBI will be also fix for merging noresume to kernel parameters with resume https://bugzilla.opensuse.org/show_bug.cgi?id=1079537
> use for resume the biggest mounted swap (bsc#1071354)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/autoyast-rnc/bootloader.rnc
> - Added tag smt to *.rnc file (bsc#1128707).
> added smt tag

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub_install.rb
Grub2 update to Factory https://build.opensuse.org/request/show/713148
> Replace --suse-signed-grub with --suse-force-signed to follow update from boo#1136601

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
> Changelog and version bump

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/finish_client.rb
- src/lib/bootloader/proposal_client.rb
- test/bootloader_finish_client_test.rb
- test/bootloader_proposal_client_test.rb
This is a port to the master branch of #575, check that pull request for the details (with screenshots).
> Do not abort the upgrade if previous Grub config is broken (master)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub_install.rb
- test/grub_install_test.rb
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1167015
trello: https://trello.com/c/b1jtZQ8R/1816-sles15-sp2-p2-1167015-a64fx-uefi-does-not-boot-grub-after-installation
> Arm workaround

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2efi.rb
- test/grub2_efi_test.rb
L3: https://bugzilla.suse.com/show_bug.cgi?id=1172720
> Efi dos label

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/autoyast-rnc/bootloader.rnc
> Drop suse_btrfs element (master)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/autoyast-rnc/bootloader.rnc
fix for https://bugzilla.suse.com/show_bug.cgi?id=1177058
> Fix schema

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2efi.rb
- test/grub2base_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1177986 and https://bugzilla.suse.com/show_bug.cgi?id=1157550#c60
> Nvram fixes

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2base.rb
- src/modules/BootArch.rb
- test/boot_arch_test.rb
Use new way how to decide if propose hibernation or not.
trello https://trello.com/c/ULBrtwpz/2144-3-couldhave-hibernation-proposed-by-installer-bootloader
jira https://jira.suse.com/browse/SLE-12280
related PR: https://github.com/yast/yast-yast2/pull/1115
> Hibernation

- test/grub2base_test.rb
fix of https://github.com/yast/yast-bootloader/pull/625
> make hibernation test proposing persistent

- src/lib/bootloader/proposal_client.rb
- test/bootloader_proposal_client_test.rb
trello: https://trello.com/c/81XcXnkb/2309-sles15-sp3-p2-1179482-disable-update-nvram-fails-in-installation-settings-window
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1179482
> fix update nvram single click action

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub_install.rb
- src/lib/bootloader/systeminfo.rb
- test/grub_install_test.rb
- test/systeminfo_test.rb
backport of https://github.com/yast/yast-bootloader/pull/635
> Backport ro efivars

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2efi.rb
Backport of https://github.com/yast/yast-bootloader/pull/646
> [WIP] Enable linuxefi/initrdefi on x86 only

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/finish_client.rb
- test/bootloader_finish_client_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1189374
> Kill mkinitrd

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/desktop/org.opensuse.yast.Bootloader.desktop
- src/lib/bootloader/finish_client.rb
- test/bootloader_finish_client_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1189915
> Fix dracut to regenerate all initrd

- package/yast2-bootloader.changes
The changelog should reference jsc#SLE- ticket number.
> Avoid jsc#PM-2612 reference

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
what was missing in https://github.com/yast/yast-bootloader/pull/654
> Updated changelog

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/udev_mapping.rb
> Fixed crash due to missing require

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/systeminfo.rb
- test/systeminfo_test.rb
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1193886
> Trusted boot impr

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- test/test_helper.rb
- Use the new YaST RSpec helper everywhere
> Unify YaST module mocking in unit tests

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/bootloader_base.rb
- src/lib/bootloader/mbr_update.rb
- test/bootloader_base_test.rb
- test/bootloader_test.rb
- test/grub2_efi_test.rb
- test/mbr_update_test.rb
Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.
> Use `Package` instead of `PackageSystem`

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2base.rb
- test/grub2base_test.rb
jira:  https://jira.suse.com/browse/SLE-22667
related: https://github.com/yast/yast-yast2/pull/1240 and https://github.com/yast/yast-installation-control/pull/122
> use product specific boot timeout proposal (jsc#SLE-22667)

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- test/autoyast_converter_test.rb
merge of https://github.com/yast/yast-bootloader/pull/666 . For description follow link.
> Resume fixes sp4

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/autoyast_converter.rb
- test/autoyast_converter_test.rb
merge of https://github.com/yast/yast-bootloader/pull/666 and https://github.com/yast/yast-bootloader/pull/667. For description follow the first link.
> Resume fixes tw

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/bootloader_base.rb
- src/lib/bootloader/grub2.rb
- src/lib/bootloader/grub2base.rb
- src/lib/bootloader/grub2efi.rb
- src/modules/Bootloader.rb
- test/grub2_efi_test.rb
- test/grub2_test.rb
- test/grub2base_test.rb
Bootloader failing on transactional system as /boot is read only.
Call specific transactional-update calls and avoid direct modification of that content.
*If the fix affects the UI attach some screenshots here.*
> Transactional

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2base.rb
- test/grub2base_test.rb
We should propose "hidden timeout" by default. [bsc#1203418](https://bugzilla.suse.com/show_bug.cgi?id=1203418)
> Fixed hidden timeout proposal

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2pwd.rb
merge of https://github.com/yast/yast-bootloader/pull/677  https://github.com/yast/yast-bootloader/pull/676 https://github.com/yast/yast-bootloader/pull/675 , description -> https://github.com/yast/yast-bootloader/pull/674
+ use the new Yast::Reducer class from https://github.com/yast/yast-yast2/pull/1277
> Merge pwd leak master

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/proposal_client.rb
- test/bootloader_proposal_client_test.rb
merge of https://github.com/yast/yast-bootloader/pull/684
> Fix migration merge

- src/lib/bootloader/autoyast_converter.rb
- src/lib/bootloader/bootloader_factory.rb
- src/lib/bootloader/finish_client.rb
- src/lib/bootloader/generic_widgets.rb
- src/lib/bootloader/systemdboot.rb
- src/lib/bootloader/systemdboot_widgets.rb
*Short description of the original problem.*
- *Bugzilla link*
- *openQA link*
- *Links to other related pull requests*
*Short description of the fix.*
- *Added a new unit test*
*If the fix affects the UI attach some screenshots here.*
> Sdbootutil

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/bootloader_factory.rb
merge of https://github.com/yast/yast-bootloader/pull/691
> Merge SLE15 SP6 branch

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/systemdboot_widgets.rb
merge of https://github.com/yast/yast-bootloader/pull/696
> Improve s390 warning master

- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2_widgets.rb
- https://trello.com/c/Kqm3HFBL
- https://bugzilla.suse.com/show_bug.cgi?id=1219989
- https://bugzilla.suse.com/show_bug.cgi?id=1222353
IBM requested even more precise wording regarding secure boot on s390.
Use suggested wording
> Secure boot update sp6

- .rubocop.yml
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/proposal_client.rb
merge of https://github.com/yast/yast-bootloader/pull/704 to SP7
> S390 sec boot sp7

- .rubocop.yml
- package/yast2-bootloader.changes
- package/yast2-bootloader.spec
- src/lib/bootloader/grub2_widgets.rb
- src/lib/bootloader/proposal_client.rb
merge of https://github.com/yast/yast-bootloader/pull/705 and https://github.com/yast/yast-bootloader/pull/704 to master
> S390 sec boot master
