yast/yast-bootloader

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/Bootloader.rb

* 4d14b64 packaging
* fe1af7e reading mountpoints correctly while clone_system

[Review] Request from 'schubi2' @ 'yast/yast-bootloader/review_150414_reading_mountpoints_correctly'

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb

os-prober is slow. Disable it on Power. boo#931653
Signed-off-by: Dinar Valeev <dvaleev@suse.com>

Disable os-prober for Power

---

agents/sysconfig.bootloader.default
agents/sysconfig.bootloader.i386

updates fillup template to properly document for what DEFAULT_APPEND stands for.

add comment for default append parameter (bnc#742715)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootStorage.rb
src/modules/Bootloader.rb

* fd3f60e packaging
* 236f06b initialize libstorage in AutoYaST config mode
* 1891022 The AutoYaST config mode does access to the system

[Review] Request from 'schubi2' @ 'yast/yast-bootloader/review_150910_autoyast_init_libstorage'

---

package/yast2-bootloader.changes
src/include/bootloader/routines/misc.rb
test/boot_common_test.rb
test/grub2pwd_test.rb

We should probably fix perl-bootloader, but this is waaay less risky.
I tested manually, but I failed to generate a sane unit test involving perl-bootloader. A full integration test would be needed... too much. :(

Workaround for bnc#945479 in SLE12

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/Bootloader.rb

* f39b604 packaging
* a39ddae Set StorageDevices flag disks_valid to true while cloning system in AutoYaST

[Review] Request from 'schubi2' @ 'yast/yast-bootloader/review_151016_autoyast_clone'

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootStorage.rb

Make sure to return a value from the loop body even if prematurely continuing with the next loop iteration; otherwise the accumulator variable ("res") will be nil for the next iteration, causing a crash.

Fixed crash in bootloader proposal if previous installation was on software RAID (bsc#955216) 

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootArch.rb

Should be more x86_64 like (quiet is needed to pass
openQA tests)

Adjust default kernel flags for aarch64

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb

Bootloader
--------------
Password protection widget in bootloader do not change for a long time from GRUB1 ages. But GRUB2 allows more fine tunning of password. In fact it contain whole user management with multiple users that can have different permissions and different passwords. For YaST we would like to keep things simplier, so we support only password for "root" user. It confuse users, so we decide to improve UX and change labeling in widget to make it more obvious for anyone using password protection. Beside it also some typos are fixed.
Before change it looks like on image below
and after change it adds more explanation to password specification. Of course also help is improved to reflect such change.

[blog] Better pwd

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootStorage.rb

The relevant keys in Storage::GetTargetMap() are named 'udev_path', not 'path'.
This is the same as https://github.com/yast/yast-bootloader/pull/325.

fix device name by-path handling (bsc#976228)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/sections.rb
src/lib/bootloader/stage1_proposal.rb
src/modules/BootStorage.rb
src/modules/Bootloader.rb
test/boot_storage_test.rb
test/stage1_test.rb

Result of profiling. After this change run of `yast2 bootloader` which write configuration spend 75% of time in grub2-install, grub2-mkconfig, grub2-set-default and writing configuration. Another 4% used for storage detection and 4% in wait loop ( sorry, was slow :wink: ). Remaining 15% is UI drawing and ruby code itself.

ruboOptimization

---

src/lib/bootloader/grub2efi.rb
src/lib/bootloader/grub_install.rb
test/grub2_efi_test.rb

With LOADER_TYPE manually set to "grub2-efi" it was erroring out in
grub_install.rb with "unsupported combination of architecture arm and
enabled EFI".
This lets `yast bootloader` save without errors.
Signed-off-by: Andreas Färber <afaerber@suse.de>

Add initial support for EFI GRUB on 32-bit ARM

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec

- Master should start using 3.2.x
- 3.1.203.x should be reserved for critical fixes in SP2 before the final release.
- 3.1.2XX shoud be reserved for fixes for Leap 42.2 before the release (also released as maint. update for SP2)
I need to correct this in order to be able to create the new branch and submit there the fix to https://bugzilla.suse.com/show_bug.cgi?id=1000629

Correct version number

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb
test/bootloader_factory_test.rb

Users sometimes reported, then when they try to tune their package selection during installation sometimes happen, that then they cannot boot. Reason is that bootloader suggest package proposal what packages he need, but user can overwrite it. To prevent this situation and to increase awareness when such situation happen, bootloader now have feature, that when it is found that required package missing, it reports error and named it. It shoud be obvious from screenshot.

Ensure correct packages

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb

...from version 3.2.3 ([PR](https://github.com/yast/yast-bootloader/pull/367)), there is a new generic solution in yast2-packager-3.2.6 ([PR](https://github.com/yast/yast-packager/pull/204))
for all YaST modules.
- 3.2.7
A screenshot from the yast2-packager PR:

Revert the package deselection check (bsc#885496)

---

.travis.yml
package/yast2-bootloader.spec
test/boot_storage_test.rb
test/boot_support_test.rb
test/bootloader_proposal_client_test.rb
test/bootloader_test.rb
test/device_map_test.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/mbr_update_test.rb
test/stage1_device_test.rb
test/stage1_test.rb
test/test_helper.rb
test/udev_mapping_test.rb

This PR obsoletes https://github.com/yast/yast-bootloader/pull/386 .

Bring unit tests back to life after storage-ng conversion

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/stage1_proposal.rb
src/modules/BootStorage.rb

This should fix the current failures in openQA when calculating the bootloader proposal. Verified to work locally.

storage-ng: fixes to work with LVM and encryption

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/Bootloader.rb
test/test_helper.rb

There's at least another Storage.InitLibstorage() in the code but it's not hit, so I leave it as is for now.

avoid call to old libstorage

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/exceptions.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2base.rb
test/grub2_widgets_test.rb

blog content
==========
As experience shown in past, writting parameters for serial console is not easy task for majority of users and anyone can make mistakes in it. The error message when wrong ones are passed is not much helpful we decide to improve it and show new nicer popup including example. We hope that you find useful this usability improvements. See in attached screenshot how it will look:

Improve ui serial console

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootStorage.rb

It looks like workaround for [bsc#950105](https://bugzilla.suse.com/show_bug.cgi?id=950105) is not needed anymore.

Do not change mode when detecting disks in AutoYaST

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/device_map_dialog.rb

it by default extend size of dialog. see old and new screenshots

Fix size of device map dialog

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/udev_mapping.rb
test/udev_mapping_test.rb

See https://bugzilla.suse.com/show_bug.cgi?id=1073254
Depends on https://github.com/yast/yast-storage-ng/pull/479
I manually tested the 13.1 -> TW upgrade including the three patches (this, https://github.com/yast/yast-storage-ng/pull/479 and https://github.com/yast/yast-update/pull/91) and it worked. :+1:

Use the new Devicegraph#find_by_any_name

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2efi.rb
src/modules/BootStorage.rb

Part of https://trello.com/c/NYy7AklQ/144-5-use-new-libstorage-ng-api-for-mount-points.

Adapt to new MountPoint API

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/Bootloader.rb
test/bootloader_test.rb

Remove calls to the old storage API. It prevents AutoYaST UI from crashing when configuring Kdump.

Remove calls to the old API

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootArch.rb
test/boot_arch_test.rb

trello: https://trello.com/c/lc9uQuDo/1415-3-15-ga-whitelist-or-blacklist-for-bug-1086665-some-boot-parameters-passed-via-parmfile-are-not-propagated-to-the-final-system-b

Parm file whitelist

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb
test/bootloader_proposal_client_test.rb

trello: https://trello.com/c/M9ahTFGe/1418-3-sle15-ga-1070233-migration-ruby-error-by-clicking-on-booting-option-when-upgrading-to-sles15
tested manually.
how it looks like:

Fix upgrade link

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/auto_client.rb
src/lib/bootloader/autoyast_converter.rb
src/lib/bootloader/bootloader_factory.rb

trello: https://trello.com/c/hjG3dkgA/1431-2-bootloader-in-autoupgrade-autoinstallation-tell-the-user-that-their-profile-is-wrong-instead-of-throwing-an-exception-please
TODO:
screenshot:

warn when autoyast have wrong loader type

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/Bootloader.rb
test/bootloader_test.rb

While calling Bootloader.Read() SCR still points to inst-sys. So we should switch to /mnt before reading the grub settings.

switching to installed system for reading grub settings

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bootloader_base.rb
src/lib/bootloader/grub2.rb
src/lib/bootloader/write_dialog.rb
src/modules/Bootloader.rb
test/bootloader_base_test.rb
test/bootloader_test.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/grub2base_test.rb

Fix for https://bugzilla.suse.com/show_bug.cgi?id=1089829
> avoiding to continue writing the configuration and reverting
the sysconfig when user rejects the installation of required package

Avoid to crash when a required package is not installed

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootStorage.rb

The same as https://github.com/yast/yast-bootloader/pull/542 but for sle12-sp4.

fix grub2 efi widget to make pmbr checkbox visible (bsc#1114932)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb
test/bootloader_proposal_client_test.rb

this is backport of SLE12 SP4 fix from https://github.com/yast/yast-bootloader/pull/524 to SLE 12 SP3 as OES needs it.

Backport booting fx

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb

The "Boot Code Options" tab does not fit the full available width when there only has the "Boot Loader" selector.
- Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1120793
- openQA: https://openqa.opensuse.org/tests/824428#step/disable_grub_timeout/7
Use the `HStretch` implicitly, aligning the widget with `Left`
Other option could be to use it explicitly, leaving the widget as it.
```ruby
...
VBox(
HBox(
LoaderTypeWidget.new,
HStretch()
),
*widgets,
VStretch()
)
...
```
| Before | After |
|--------|-------|
|  ![boot_code_options_tab_missaligned](https://user-images.githubusercontent.com/1691872/51743007-4a479f80-2093-11e9-8b9d-c9c1af91541e.png) | ![boot_loader_combo_left_aligned](https://user-images.githubusercontent.com/1691872/51742381-7f52f280-2091-11e9-91d3-06e …

Fix "Boot Code Options" tab width

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/exceptions.rb
src/modules/BootStorage.rb
test/boot_storage_test.rb

https://trello.com/c/3HUj2DWo
https://bugzilla.suse.com/show_bug.cgi?id=1122008
https://bugzilla.suse.com/show_bug.cgi?id=1116305
If a user uses a `/dev/disk/by-path/...` device name (YaST never does that by itself!) for the bootloader configuration, that device name may have become invalid upon a future reboot. That doesn't take much: If the hardware changes only slightly, if the kernel parameters change, the kernel may decide to change the numbering scheme for devices, and so this kind of device name may change, making the old device name invalid.
This caused a hard to understand error message:
```
Internal error. Please report a bug report with logs.
Run save_y2logs to get complete logs.
Details: Error reading the bootloader configuration files.
Please use YaST2 bootloader to fix it. …
```

Better Error Handling for Broken by-path Device Names

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb

After changes introduced in #549, @rwx788 [realized that the interface was a bit worse than previous](https://bugzilla.suse.com/show_bug.cgi?id=1120793#c10) (mainly due to a couple of miss-alignments).
Make necessary adjustments to have a more consistent layout.
A validation from @rwx788, discussed on IRC
|               | Before | After |
|---------------|--------|-------|
| Grub2         | ![ncurses_bootloader_grub2_before](https://user-images.githubusercontent.com/1691872/52463818-5beb7580-2b70-11e9-872c-8f7d08b432c2.png) | ![ncurses_bootloader_grub2_after](https://user-images.githubusercontent.com/1691872/52463849-7291cc80-2b70-11e9-9e03-ef451c5b1458.png) |
| Grub2 for EFI | ![ncurses_bootloader_grub2efi_before](https://user-images.githubusercontent.com/1691872/52463892-99500300-2b70-1 …

Layout adjustments

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
test/grub2base_test.rb

trello: https://trello.com/c/ZkdxYmxN/716-1-sles15-sp1-p2-1124064-internal-error-while-opening-yast2-boot-loader-module
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1124064

do not crash if grub.cfg is missing

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/boot_record_backup.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1127138
- https://trello.com/c/plarcsbX/770-1-sle15-sp1-no-mkdir-is-not-in-usr-sbin

Correct program paths

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
src/lib/bootloader/serial_console.rb
test/grub2base_test.rb
test/serial_console_test.rb

https://trello.com/c/HJUJHx0Y/
https://bugzilla.suse.com/show_bug.cgi?id=1080928
When installing with a serial console, console output for a XEN DOM0 kernel is not also redirected to the serial console.
Add some parameters to the GRUB2 configuration to propagate the information about the serial console also to the XEN DOM0 kernel:
```
GRUB_CMDLINE_XEN_DEFAULT="console=com1 com1=57600"
GRUB_CMDLINE_LINUX_XEN_REPLACE_DEFAULT="console=hvc0"
```
...if the host kernel used
```
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=57600 --parity=no"
```
See also the discussion in the bug.
- New unit tests
- Manual test with my (now freshly extended) virt-installer script which uses virt-install/QEMU:
- with serial console
- without serial console
Used ISO: …

Propagate serial console params to XEN kernels (bsc#1080928)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootSupportCheck.rb

> the warning popup text is too long even for a graphical screen. It should be formatted properly.
- https://bugzilla.suse.com/show_bug.cgi?id=1136746
- https://trello.com/c/0HdoeUm7/1040-sle12-sp5-bootloader-warning-popup-when-starting-to-install-is-too-wide-and-does-not-fit-screen
To split it in multiple lines.
<details>
<summary>Click to show/hide some screenshots</summary>
* How it currently looks
* Proposal
| ![bootloader_proposal_message_reformated](https://user-images.githubusercontent.com/1691872/58556162-32378680-8213-11e9-8efc-2b3fa0121d7d.png) | ![ncurses_bootloader_proposal_message_reformated_2](https://user-images.githubusercontent.com/1691872/58556176-3bc0ee80-8213-11e9-959c-347e68474cd8.png) |
|---|---|
</details>
Version bump not required (not bsc/fate number available). …

Split the description of technical problem in multiple lines 

---

Dockerfile
Rakefile

`Rakefile` and `Dockerfile` were not adapted to use `SLE-12-SP5`
I realized about it trying to do an SR via `rake osc:sr`, which actually generated a [MR for SLE-12-SP4](https://build.suse.de/request/show/193762) (already revoked).
Properly adapt those files.

Adapt Rakefile and Dockerfile for SLE-12-SP5

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2efi.rb
src/lib/bootloader/grub_install.rb
src/lib/bootloader/sysconfig.rb
test/grub2_efi_test.rb
test/sysconfig_test.rb

https://bugzilla.suse.com/show_bug.cgi?id=1136601
Not tested yet

[RFC] Enable secureboot on aarch64 (boo#1136601)

---

.rubocop.yml
package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/autoyast-rnc/bootloader.rnc
src/lib/bootloader/autoyast_converter.rb
src/lib/bootloader/config_dialog.rb
src/lib/bootloader/cpu_mitigations.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2base.rb
src/lib/bootloader/proposal_client.rb
src/modules/BootArch.rb
src/modules/Bootloader.rb
test/autoyast_converter_test.rb
test/boot_arch_test.rb
test/bootloader_proposal_client_test.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/grub2base_test.rb

trello: https://trello.com/c/FOEGCWZ1/1082-jscsle-7078-backport-kernel-mitigation-settings-from-15-sp1-to-12-sp5
Related PRs:
- https://github.com/yast/yast-packager/pull/454
- https://github.com/yast/yast-update/pull/130
- https://github.com/yast/yast-network/pull/849
- installation-control TODO
- yast-schema TODO
AIs:

Backport cpu mitigations

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec

- The recent fix in YaST RPM macros now updates the desktop files
- The `%suse_update_desktop_file` macro is defined in the `update-desktop-files` package
- Without it the macro is not expanded and the shell treats `%` as a job control character and fails with error `fg: no job control`

Added "BuildRequires: update-desktop-files"

---

src/lib/bootloader/finish_client.rb
src/lib/bootloader/proposal_client.rb
test/bootloader_finish_client_test.rb
test/bootloader_proposal_client_test.rb

Reported as [bug#1138930](https://bugzilla.suse.com/show_bug.cgi?id=1138930) which was closed because the system under test was indeed broken.
When upgrading a system which contains a badly broken Grub2 configuration (e.g. contains references to udev links that do not longer exist), the process could indeed go wild in several points. All of them resulted in the upgrade being interrupted with an ugly internal error.
The first problem could arise in the summary screen. Like shown in this screenshots.
If the error didn't pop-up or if user managed to recover from it, it was possible to reach the final phase of the upgrade process. But then the following internal error popped up.
For more details see https://trello.com/c/MMbbUuwZ/1140-2-sle12-sp5-p2-1138930-build-00770201-openqa-test-fails-in-a …

Do not abort the upgrade if previous Grub config is broken

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/autoyast-rnc/bootloader.rnc
src/lib/bootloader/autoyast_converter.rb
test/autoyast_converter_test.rb

https://trello.com/c/i6UZefuO/1341-feature-jscsle-8787-autoyast-option-for-non-secure-boot
JSC#SLE-8787

Autoyast secure boot

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
test/grub2base_test.rb

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1100755
Goal: handle nicely if /etc/default/grub missing.

Handle more missing files

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/config_dialog.rb

Improve the message when the root file system is not found. Now it suggests to unmount bind-mounted devices.
See https://bugzilla.suse.com/show_bug.cgi?id=1160176#c5 and https://github.com/yast/yast-bootloader/pull/586.

Improve error message for missing root 

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/udev_mapping.rb
test/udev_mapping_test.rb

This module and *yast2-storage-ng* have a very similar logic to obtain the most reasonable udev link of a device. Such duplication (as every code/logic duplication) is error prone.
Now on, yast2-bootloader simply delegates the logic to obtain an udev link to yast2-storage-ng module.
These changes require https://github.com/yast/yast-storage-ng/pull/1050.
Added new unit tests.

Delegate mount by logic

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/autoyast_converter.rb
src/lib/bootloader/grub2.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2base.rb
src/lib/bootloader/grub2efi.rb
src/lib/bootloader/grub_install.rb
src/lib/bootloader/proposal_client.rb
src/lib/bootloader/sysconfig.rb
src/lib/bootloader/systeminfo.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/grub_install_test.rb
test/systeminfo_test.rb

- https://jira.suse.com/browse/SLE-9471
- https://jira.suse.com/browse/SLE-9425
Implement secure boot handling for s390.
- extend existing secure boot logic to s390
- bundle a number of system-dependend logic around secure boot into a new `Systeminfo` class
- use `/etc/sysconfig/bootloader::SECURE_BOOT` to store the setting; `grub2-install` is expected to read it from there
- the secure boot setting can be changed directly from the installation summary screen
- to match it visually, the same has been done for trusted boot
- when the secure boot setting is changed, a popup is shown on s390 to remind the admin to 
adjust the HMC
- on s390, start with the currently active secure boot setting; not the value from sysconfig; this way the user doesn't run into problems when the sysconfig value …

support s390 secure boot (jsc#SLE-9425)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/proposal_client.rb
src/lib/bootloader/systeminfo.rb
test/systeminfo_test.rb

- https://trello.com/c/7ZxtAqIG
Handle new Secure Boot setting for zSeries (z15+) in YaST.
- this is a follow-up to https://github.com/yast/yast-bootloader/pull/592
- technical summary: https://bugzilla.suse.com/show_bug.cgi?id=1166736#c9
- if `/sys/firmware/ipl/has_secure` is 1, the proposal will enable secure boot support
- the current state is stored in `/etc/sysconfig/bootloader::SECURE_BOOT` ("yes" or "no")
- the user may change the setting
- there is a warning about z15+ requirement if secure boot support is turned on
- reworked help texts to try to explain the situation

support s390 secure boot (jsc#SLE-9425, jsc#SLE-9471, bsc#1166736)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/systeminfo.rb
test/systeminfo_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1168165
- https://trello.com/c/W1LvJYKF
Secure boot is only possible on SCSI disks.
There are two options to deal with this
1. Hide the 'secure boot' check box when zipl is not on a SCSI disk.
2. Uncheck 'secure boot' when zipl is not on a SCSI disk.
I went for 2. basically so it is still possible to influence the secure boot setting. Otherwise the user might get stuck if `/etc/sysconfig/bootloader::SECURE_BOOT` is `yes` for whatever reason and they can't disable it because the UI hides the option for that.
How best to check for SCSI devices? See
- https://github.com/yast/yast-bootloader/blob/4226947aba875921b82d5dff4f2c64c07047d759/src/lib/bootloader/systeminfo.rb#L139-L141
- Answered: https://bugzilla.suse.com/show_bug.cgi?id=1168165#c11
Nice …

limit s390 secure boot to SCSI disks (bsc#1168165)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/proposal_client.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1168165#c14
Update the s390x secure boot warning message.

update s390x secure boot message (bsc#1168165)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/desktop/org.opensuse.yast.Bootloader.desktop

Sets the `AutoInstClonable` attribute as the special handling for this section was removed at https://github.com/yast/yast-autoinstallation/pull/604.

Set autoinst clonable

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/autoyast-rnc/bootloader.rnc

trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on https://github.com/yast/yast-autoinstallation/pull/598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.

allow optional types for string and map

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/systeminfo.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1171821
- https://trello.com/c/fBJvEssp
Detection if secure boot is available fails if zipl is going to be installed on a multipath device.
Secure boot (or rather the new loader format) works only for SCSI disks. Enhance the disk type detection to cover cases where the device is a device mapper target by checking also udev device links.
```xml
<Multipath>
<sid>50</sid>
<name>/dev/mapper/36005076309ffd435000000000000803e</name>
<sysfs-name>dm-0</sysfs-name>
<sysfs-path>/devices/virtual/block/dm-0</sysfs-path>
<region>
<length>41943040</length>
<block-size>512</block-size>
</region>
<topology/>
<udev-id>scsi-36005076309ffd435000000000000803e</udev-id>
<udev-id>wwn-0x6005076309ffd435000000000000803e</udev-id> …
```

s390 secure boot: enhance disk type detection to cover multipath (bsc#1171821)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub_install.rb
test/grub_install_test.rb

bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1172114
It is SLE15 SP2 only as it is intended as workaround till new shim will appear. Fix of https://github.com/yast/yast-bootloader/pull/600

Fix efivars workaround

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/sysconfig.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1171912
The comments for `SECURE_BOOT` and `TRUSTED_BOOT` in `/etc/sysconfig/bootloader` are outdated:
-  `SECURE_BOOT` is also available on IBM z15
- `TRUSTED_BOOT` also works on UEFI systems ([bsc#1036735](https://bugzilla.suse.com/show_bug.cgi?id=1036735))

update comments in /etc/sysconfig/bootloader (bsc#1171912)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/auto_client.rb
src/lib/bootloader/autoinst_profile/bootloader_section.rb
src/lib/bootloader/autoinst_profile/device_map_entry_section.rb
src/lib/bootloader/autoinst_profile/global_section.rb
src/lib/bootloader/autoyast_converter.rb
src/modules/Bootloader.rb
test/autoyast_converter_test.rb
test/bootloader/auto_client_test.rb
test/bootloader/autoinst_profile/bootloader_section_test.rb
test/bootloader/autoinst_profile/device_map_entry_section_test.rb
test/bootloader/autoinst_profile/global_section_test.rb
test/bootloader_test.rb
test/test_helper.rb

Problem
==============
Each module (storage, firewall,network) has his own AutoYaST Issue and profile handling which is incompatible and doubles the code.
bsc#1171335
Solution
========
Bring base classes to yast2 package and cleanup the code of the other packages which will use
these common base classes:
yast/yast-yast2#1050
yast/yast-yast2#1055

Cleanup issue handling

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
test/grub2base_test.rb

A unit test is failing in OBS when running on a s390 machine:
~~~
[   29s] Failures:
[   29s] 
[   29s]   1) Bootloader::Grub2Base#propose xen hypervisor kernel parameters proposal propose vga parameter if there is framebuffer
[   29s]      Failure/Error: expect(subject.grub_default.xen_hypervisor_params.parameter("vga")).to eq "gfx-1024x768x16"
[   29s] 
[   29s]        expected: "gfx-1024x768x16"
[   29s]             got: false
[   29s] 
[   29s]        (compared using ==)
[   29s] 
[   29s]        Diff:
[   29s]        @@ -1,2 +1,2 @@
[   29s]        -"gfx-1024x768x16"
[   29s]        +false
[   29s]      # ./test/grub2base_test.rb:356:in `block (4 levels) in <top (required)>'
[   29s] 
[   29s] Finished in 5.7 seconds (files took 0.92165 seconds to load)
[   29s] 581 examples, 1 …

Avoid unit test failure

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootArch.rb

This is needed for https://github.com/yast/yast-installation/pull/873 to make it possible to manipulate the `rd.zdev` kernel option.

add rd.zdev to allowed kernel options on s390 (bsc#1168036)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/autoyast-rnc/bootloader.rnc

The `<suse_btrfs>` is not needed anymore. See https://github.com/yast/yast-bootloader/blob/7f9bc8c0184f0f5586692ecd7283d25d656caca6/src/lib/bootloader/grub2base.rb#L163 for further information.

Drop suse_btrfs element

---

.rubocop.yml
package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/proposal_client.rb
src/lib/bootloader/stage1.rb
src/modules/BootStorage.rb

This change is based on jira https://jira.suse.com/browse/SLE-16033 and original bug report https://bugzilla.suse.com/show_bug.cgi?id=1165042 . Basically issue is when partition for booting is on logical partition, then it needs in some cases stage1 written to extended and in some cases in logical partition, depending on machine BIOS. Still we propose to use disk MBR for stage1 but allow easier way to select extended or logical partition, when user wants to.
The change is visible only when partition is logical, otherwise it looks same as before.
Another change is also clarification of summary line with stage 1 location ( see screenshots ).
So here is comparison of summary - it change wording from "Status Location" to "Write Boot Code To" and allows links to boot from logical or extended …

Boot code location

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2.rb
src/lib/bootloader/grub2_widgets.rb

Goal of this pull request is to make installation summary and UI of bootloader more consistent.
Lets start from the end. We discuss two approaches describe below and result of discussion with UX team is to use the first one and just adjust a bit wording. So final result is this one:
From discussion in yast team we try two approaches. One is current one just with better wording and the second one is to use in summary checkbox like approach which reduce text and make it more looking like checkbox configuration.
Example of approach 1:
qt 
ncurses
example of approach 2:
qt
ncurses
if we use approach 2 we probably should also make current defails more consistent and remove that write into from
but as said above approach 1 wins as it is more explicit for users what exactly happen and what is …

use more consistent wording

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb
test/bootloader_proposal_client_test.rb

YaST bootloader cannot properly update its proposal to reflect changes in the swap configuration. That's visible in two situations reported as separate bug reports:
- If the swap partition is substituted with another with a different name, the `resume=` parameter gets duplicated (one with the previous name and another with the current one) - [bsc#1180218](https://bugzilla.suse.com/show_bug.cgi?id=1180218)
- If the swap partition is deleted, the `resume=` parameter is not removed - [bsc#1180976](https://bugzilla.suse.com/show_bug.cgi?id=1180976)
In theory, the bootloader proposal should be totally discarded and recreated from scratch every time the storage setup changes. But there was an error in the code and the change was generally not detected.
Fixed the detection of changes in storage. …

Fix recalculation when storage has changed (bsc#1180218, bsc#1180976)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
src/modules/BootStorage.rb
test/grub2base_test.rb

When the swap is smaller than the RAM size, suspending to RAM could not work. But the *resume=* kernel parameter is being added even in that cases.
* https://bugzilla.suse.com/show_bug.cgi?id=1180977
* https://trello.com/c/VkjmNIRr/2279-3-yast-bootloader-adds-the-resume-parameter-when-it-shouldnt
The *resume=* kernel parameter is not added if the swap size is smaller than the RAM size.

Do not add resume when swap is too small

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2efi.rb
src/lib/bootloader/grub_install.rb
src/lib/bootloader/systeminfo.rb
test/grub_install_test.rb
test/systeminfo_test.rb

trello: https://trello.com/c/E4U5cNa9/2289-3-feature-musthave-secure-boot-support-in-yast-on-aarch64
jsc: https://jira.suse.com/browse/SLE-15823
Testing: Only unit tested as failed to test secure boot in qemu and do not have hardware around that allows such test.

use shim also on aarch (jsc#SLE-15020)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub_install.rb
src/lib/bootloader/systeminfo.rb
test/grub_install_test.rb
test/systeminfo_test.rb

Issue: Checking just for presence of efivars is not enough as it can be mounted as read only for whatever reason.
Fix: Check also if it is mounted as readwrite.
Tested also manually with rw efivars and works.
related PBIs: 
https://trello.com/c/GSWoJy3g/2305-sles15-sp3-p1-1182749-secure-boot-is-enabled-on-aarch64-even-when-disabled-on-test-machine
https://trello.com/c/ru1DFOGu/2313-bug-1174111-jetson-agx-xavier-grub2-install-could-not-prepare-boot-variable-invalid-argument

Ro efivars

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/device_map_dialog.rb

trello: https://trello.com/c/LOBnWzcU/2338-publicsles-15-sp3-p5-1183218-build-1585-no-grub-related-warnings-where-number-of-devices-exceeds-8
bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1183218

Device map dialog validation

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
test/grub2_widgets_test.rb

bsc: https://bugzilla.suse.com/show_bug.cgi?id=1184968
issue is that cpu mitigation does not expect to be used outside of grub2 bootloader. So I adapt it.

Fix cpu mitigation sp3

---

.rubocop.yml
package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub_install.rb
src/lib/bootloader/systeminfo.rb

Backport https://github.com/yast/yast-bootloader/pull/641 to SLE15-SP3 / Leap 15.3

arm can boot on uefi

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bootloader_factory.rb
src/modules/BootArch.rb
src/modules/BootSupportCheck.rb

This is a follow-up of https://github.com/yast/yast-bootloader/pull/641

Fixes for 'arm can boot on uefi'

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2base.rb
src/lib/bootloader/os_prober.rb
test/bootloader/auto_client_test.rb
test/bootloader_proposal_client_test.rb
test/bootloader_test.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/grub2_widgets_test.rb
test/os_prober_test.rb

_**This is the fix for the SLE-15-SP3 branch. The port to the master branch will follow.**_
https://trello.com/c/OVhSxr2e/2493-3-sle15-sp3-1186369-yast2-bootloader-probe-foreign-os-doesnt-detect-add-windows
https://bugzilla.suse.com/show_bug.cgi?id=1186369
No selection for a parallel-boot Windows in the Grub boot menu after a SLES-15-SP3 installation.
The `os-prober` package is no longer installed by default, unlike in previous releases.
Now explicitly adding the `os-prober` package to the set of packages to install, unless
- the package is not available (not provided by the current product)
- on s/390
In the UI also no longer offering that _Probe Foreign OS_ check box if the package is not available.
Does it make sense to do that on EFI boot as well? Not sure.
However, the _Probe Foreign …

Add os-prober package (SLE-15-SP3)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2base.rb
src/lib/bootloader/os_prober.rb
test/bootloader/auto_client_test.rb
test/bootloader_proposal_client_test.rb
test/bootloader_test.rb
test/grub2_efi_test.rb
test/grub2_test.rb
test/grub2_widgets_test.rb
test/os_prober_test.rb

Basically, it _Add os-prober package_ in `master` branch (apart of syncing changes with `SLE-15-SP3`). See https://github.com/yast/yast-bootloader/pull/649 for more details.

Merge SLE-15-SP3 into master

---

src/lib/bootloader/device_path.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/stage1.rb
src/lib/bootloader/udev_mapping.rb
test/device_path_test.rb

bnc#1092950
User entered device specification as UUID="<uuid_of_a_device>" and bootloader module crashed with internal error
1) User's input is validated and an error is reported if the path is invalid
2) strings UUID="<uuid_of_a_device>" or LABEL="<device_label>" are translated to an absolute path (/dev/...)

Custom device path validation / conversion. 

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bootloader_factory.rb
src/lib/bootloader/systeminfo.rb
src/modules/BootSupportCheck.rb
test/boot_support_test.rb
test/systeminfo_test.rb

- https://trello.com/c/ZWMQnKom
- https://bugzilla.suse.com/show_bug.cgi?id=937067
EFI detection code is all over the place. Consolidate in one spot.
Use latest `Y2Storage::Arch` class to determine UEFI boot support.
- https://github.com/yast/yast-storage-ng/pull/1256

rely on yast-storage-ng to detect UEFI boot support status (bsc#937067)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub_install.rb
src/lib/bootloader/systeminfo.rb
test/grub_install_test.rb
test/systeminfo_test.rb

This adds powerpc secure boot detection support to systeminfo and grub
install.
Currently we have secure boot support indicated by ibm,secure-boot file
presence but in many configurations this file is present but secure boot
cannot work.
We should propose secure boot on powerpc when and only when content of
this file is non-zero because then booting without secure boot will
fail.
On the other hand we should enable the user to manually turn on secure 
boot when ibm,secure-boot is present or even in all cases.
In the future it is expected that the firmware grows something like 
efivarfs allowing the OS to pass additional parameters to the secure 
bootloader which should make the secure boot reliable.
See also https://github.com/openSUSE/perl-bootloader/pull/137

Support powerpc secure boot (bsc#1192764 jsc#SLE-18271).

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2pwd.rb
test/grub2pwd_test.rb

yast2-bootloader does not work inside a container out of the box (see [bsc#1199840](https://bugzilla.suse.com/show_bug.cgi?id=1199840)). There are several things that need to be fixed:
1) storage-ng probing must work. See https://github.com/yast/yast-in-container/pull/10
2) The command `grub2-mkpasswd-pbkdf2` is executed locally (ie. in the container) instead of the target system due to [historical reasons](https://bugzilla.suse.com/show_bug.cgi?id=900039) that do not longer apply.
3) Problems installing the needed packages.
As mentioned, the first problem is addressed in a separate pull request at another repository.
This fixes the second problem by making sure `grub2-mkpasswd-pbkdf2` is executed in the target system.
Problem 3 remains to be fixed (and likely will be addressed by an …

Adaptations to work inside a container

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb

- https://trello.com/c/W6CKhmvf
- https://bugzilla.suse.com/show_bug.cgi?id=1197608
Help text mentions `trustedgrub2` even if not applicable.
Don't mention it.
If someone wants to completely reword that help text, I'm open for suggestions.

adjust trusted boot help text (bsc#1197608)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2.rb
test/grub2_test.rb

when testing I found that on transactional system stage1 location is not written down, so bootloader module does not know where previously was stage1 written.
write such info even on transactional systems. It was accidentally skipped as only grub2-install should be skipped.
- *Added a new unit test*

Transactional stage1

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2pwd.rb

Grub2 password is logged to yast logs in plain text when doing encryption.
- https://bugzilla.suse.com/show_bug.cgi?id=1201962
Note: SLE15-SP1 is the first affected code stream as previously is used WFM.Execute which does not logs. And it is still in some LTSS supported.
Do not log stdin for command to generate encrypted password.
- *Tested manually* as unit tests for writting to logs is quite fragile.

Pwd leak sp1

---

package/yast2-bootloader.changes
src/lib/bootloader/grub2pwd.rb
src/lib/bootloader/grub_install.rb

port of https://github.com/yast/yast-bootloader/pull/675 and https://github.com/yast/yast-bootloader/pull/674
a bit tricky as previously merge from SP2 was not done, so it needs a bit more conflict solving

Merge pwd leak sp3

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
src/lib/bootloader/systeminfo.rb
test/systeminfo_test.rb

secure boot on ppc works differently than on other architectures. It checks if hardware has enforced signed kernel and only in that case propose to use it and also only in that case is checkbox checked even if OS is set to install signed kernel.
bug(private): https://bugzilla.suse.com/show_bug.cgi?id=1206295
replaces https://github.com/yast/yast-bootloader/pull/679
Make it consistent with other architectures and reflect only OS state and propose secure boot when it is supported.
- *Adapted unit test*

Secure ppc2

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2base.rb
src/lib/bootloader/systeminfo.rb
test/systeminfo_test.rb

backport of https://github.com/yast/yast-bootloader/pull/680 to SLE15 SP4 as requested in https://bugzilla.suse.com/show_bug.cgi?id=1206295

Backport ppc secure

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/proposal_client.rb
test/bootloader_proposal_client_test.rb

User selection was ignored during migration.
- https://bugzilla.suse.com/show_bug.cgi?id=1210811
Drop legacy code for SLE11 migration and reset proposal only if it is forced.
- manually

Fix migration sp5

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootArch.rb
test/boot_arch_test.rb

The zFCP kernel module enables the *allow_lun_scan* option by default (since SLE 12). But that option can be disabled by means of the *zfcp.allow_lun_scan=0* kernel parameter. If *auto_lun_scan* is configured, then the kernel option has to be persisted in the target system.
See https://github.com/openSUSE/agama/pull/626.
Adds *zfcp.allow_lun_scan* kernel option to the list of options to persist on s390 arch.
* Added a new unit test

Persist zfcp.allow_lun_scan kernel option

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
test/bootloader_factory_test.rb

Testsuite was broken for architectures other than x86_64 while checking the supported bootloaders.

fixed test for checking -supported_names-

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bootloader_factory.rb
src/lib/bootloader/grub2efi.rb
src/lib/bootloader/grub_install.rb
src/lib/bootloader/systeminfo.rb

SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
- https://github.com/yast/yast-bootloader/pull/683 backported
- https://github.com/yast/yast-bootloader/pull/687 as it is agama only is not backported to avoid side-effect in SLE15
- https://github.com/yast/yast-bootloader/pull/685 is already in SP5

Backport sp6

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bootloader_factory.rb

insts-sys does not have sysconfig for bootloader. The code first try to get bootloader name from system and then translate it to object. Sadly that name is not checked if it is defined and it result in unnecessary error in yast logs.
Check if bootloader name is defined and if not, then just return nil to activate condition at https://github.com/yast/yast-bootloader/blob/master/src/lib/bootloader/bootloader_factory.rb#L42 to use proposed bootloader instead.
- *Tested manually* ( official SP6 medium and yupdate from this branch and then on proposal screen check yast logs that it does not contain `/tmp/var/log/YaST2/y2log-2.gz:2023-12-16 06:53:34 <3> install(4251) [Ruby] bootloader/bootloader_factory.rb(bootloader_by_name):84 Factory receive nil name`

Fix nil factory

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/modules/BootArch.rb

The cio_ignore kernel argument is ignored on s390 when the parameters are read and later it is not written properly (see https://github.com/yast/yast-installation/pull/1104 for more details).
- https://bugzilla.suse.com/show_bug.cgi?id=1210525
Whitelist the cio_ignore parameter on s390.

Allow cio_ignore kernel argument on s390 (bsc#1210525)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/systemdboot.rb
src/lib/bootloader/systemdboot_widgets.rb
test/systemdboot_widgets_test.rb

Feature: Do not timeout boot menue in systemd-boot. (bsc#1216366)

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb

merge of https://github.com/yast/yast-bootloader/pull/698

Secure boot update master

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/systemdboot.rb
test/systemdboot_test.rb

* sdbootutil needs the root entry in /etc/kernel/cmdline in order to write the correct bootloader menu entry.
* /etc/kernel/cmdline has to be written before sdbootutil will be called.
- Adapted test cases.
- Tested manually in MicroOS(including transactional-update) and TW (while installation and in the installed system).

Writing "root" entry into /etc/kernel/cmdline which is needed by sdbootutil

---

package/yast2-bootloader.changes
src/lib/bootloader/autoyast_converter.rb
src/lib/bootloader/systemdboot.rb
src/lib/bootloader/systemdboot_widgets.rb
src/lib/cfa/systemd_boot.rb
test/autoyast_converter_test.rb
test/cfa/systemd_boot_test.rb
test/systemdboot_test.rb
test/systemdboot_widgets_test.rb

I think that Menü has been used as menue in the code as a German translation, creating a variable menue_timeout. Also menue is used in error messages.
This commit rename menue to menu, including the error messages presented to the user.

Rename menue_timeout to menu_timeout

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/systeminfo.rb
test/grub2_efi_test.rb
test/systeminfo_test.rb

32 bit arm and also riscv64 does not have shim and due to this we do not support secure boot on them (as opposite to s390 and ppc with own secure boot way ). But bootloader propose secure boot there, resulting in perl-bootloader failure.
https://bugzilla.suse.com/show_bug.cgi?id=1229070
disable secure boot support on given architectures.
- *Added a new unit test*

Disable secure boot 32b arm

---

.rubocop.yml
package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/proposal_client.rb

The text in proposal popup regarding s390 is still not precise. On running system it is correct.
Keep the text in sync and also note it in code to avoid such issue next time.
- no testing as it is just text change and text is identical and both parts use dialog, so it should also fit.

S390 sec boot2

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/bls.rb
test/bls_test.rb

sdbootutil set-timeout will be called with the wrong parameter
- BSC#1236578
- https://openqa.opensuse.org/tests/4813605
Fixed parameters
- Tested manually

Calling -sdbootutil set-timeout- with the correct parameters

---

package/yast2-bootloader.changes

The latest version of
/usr/lib/obs/service/source_validators/helpers/fix_changelog
blames old entries which have the wrong format.

fixed build

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/grub2bls.rb
src/lib/bootloader/systemdboot.rb

security=selinux selinux=1 is not available while installing the bootloader
https://bugzilla.suse.com/show_bug.cgi?id=1244399
Writing kernel parameter BEFORE installing the bootloader

Fixed: Installations by YaST with BLS do not have SELinux enabled

---

package/yast2-bootloader.changes
package/yast2-bootloader.spec
src/lib/bootloader/generic_widgets.rb
src/lib/bootloader/grub2_widgets.rb
src/lib/bootloader/grub2bls.rb
src/lib/bootloader/systemdboot.rb
src/lib/bootloader/systemdboot_widgets.rb
src/lib/bootloader/systeminfo.rb
test/generic_widgets_test.rb
test/grub2_bls_test.rb
test/grub2_widgets_test.rb
test/systemdboot_test.rb

Now grub2-bls and systemd-boot supports "update nvram". This option can be set in the UI now.
- https://bugzilla.opensuse.org/show_bug.cgi?id=1228595
- https://bugzilla.opensuse.org/show_bug.cgi?id=1247952
Added this option in the UI
- Added a new unit test
- Tested manually

"update nvram" option added in grub2-bls and systemd-boot
